# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 741)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_menu = QtWidgets.QWidget(self.widget)
        self.widget_menu.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_menu.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_menu.setStyleSheet("QWidget#widget_menu{background:qlineargradient(spread:pad,x1:0,y1:0,x2:1,y2:0,stop:0 #4e54c8,stop:1 #8f94fb);}")
        self.widget_menu.setObjectName("widget_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget_menu)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_logo = QtWidgets.QLabel(self.widget_2)
        self.label_logo.setMinimumSize(QtCore.QSize(150, 49))
        self.label_logo.setMaximumSize(QtCore.QSize(150, 49))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_logo.setFont(font)
        self.label_logo.setStyleSheet("QLabel{background:Transparent;color:white}")
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap(":/images/toodo.fun.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo.setObjectName("label_logo")
        self.horizontalLayout_3.addWidget(self.label_logo)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget_menu)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_menu_soft = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_menu_soft.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_menu_soft.setFont(font)
        self.pushButton_menu_soft.setStyleSheet("QPushButton{background:Transparent;color:white;}QPushButton:hover{background-color:rgba(0,0,0, 0.2);}")
        self.pushButton_menu_soft.setObjectName("pushButton_menu_soft")
        self.verticalLayout.addWidget(self.pushButton_menu_soft)
        self.pushButton_menu_source = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_menu_source.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_menu_source.setFont(font)
        self.pushButton_menu_source.setStyleSheet("QPushButton{background:Transparent;color:white;}QPushButton:hover{background-color:rgba(0,0,0, 0.2);}")
        self.pushButton_menu_source.setObjectName("pushButton_menu_source")
        self.verticalLayout.addWidget(self.pushButton_menu_source)
        self.pushButton_menu_article = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_menu_article.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_menu_article.setFont(font)
        self.pushButton_menu_article.setStyleSheet("QPushButton{background:Transparent;color:white;}QPushButton:hover{background-color:rgba(0,0,0, 0.2);}")
        self.pushButton_menu_article.setObjectName("pushButton_menu_article")
        self.verticalLayout.addWidget(self.pushButton_menu_article)
        self.pushButton_menu_api = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_menu_api.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_menu_api.setFont(font)
        self.pushButton_menu_api.setStyleSheet("QPushButton{background:Transparent;color:white;}QPushButton:hover{background-color:rgba(0,0,0, 0.2);}")
        self.pushButton_menu_api.setObjectName("pushButton_menu_api")
        self.verticalLayout.addWidget(self.pushButton_menu_api)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.pushButton_menu_about_us = QtWidgets.QPushButton(self.widget_menu)
        self.pushButton_menu_about_us.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_menu_about_us.setFont(font)
        self.pushButton_menu_about_us.setStyleSheet("QPushButton{background:Transparent;color:white;}QPushButton:hover{background-color:rgba(0,0,0, 0.2);}")
        self.pushButton_menu_about_us.setObjectName("pushButton_menu_about_us")
        self.verticalLayout_2.addWidget(self.pushButton_menu_about_us)
        spacerItem = QtWidgets.QSpacerItem(20, 460, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_sys_info = QtWidgets.QLabel(self.widget_menu)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_sys_info.setFont(font)
        self.label_sys_info.setStyleSheet("QLabel{background:Transparent;color:white}")
        self.label_sys_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sys_info.setObjectName("label_sys_info")
        self.verticalLayout_2.addWidget(self.label_sys_info)
        self.horizontalLayout_2.addWidget(self.widget_menu)
        self.widget_main = QtWidgets.QWidget(self.widget)
        self.widget_main.setStyleSheet("QWidget#widget_main{background:#F7FAFF}")
        self.widget_main.setObjectName("widget_main")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_main)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_top = QtWidgets.QWidget(self.widget_main)
        self.widget_top.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_top.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget_top.setObjectName("widget_top")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_top)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(886, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.widget_6 = QtWidgets.QWidget(self.widget_top)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_feedback = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_feedback.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_feedback.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_feedback.setStyleSheet("QPushButton{background:Transparent;color:blank;}QPushButton:hover{background-color:rgba(0,0,0, 0.1);}")
        self.pushButton_feedback.setText("")
        self.pushButton_feedback.setObjectName("pushButton_feedback")
        self.horizontalLayout_4.addWidget(self.pushButton_feedback)
        self.pushButton_update = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_update.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_update.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_update.setStyleSheet("QPushButton{background:Transparent;color:blank;}QPushButton:hover{background-color:rgba(0,0,0, 0.1);}")
        self.pushButton_update.setText("")
        self.pushButton_update.setObjectName("pushButton_update")
        self.horizontalLayout_4.addWidget(self.pushButton_update)
        self.pushButton_min = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_min.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_min.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_min.setStyleSheet("QPushButton{background:Transparent;color:blank;}QPushButton:hover{background-color:rgba(0,0,0, 0.1);}")
        self.pushButton_min.setText("")
        self.pushButton_min.setObjectName("pushButton_min")
        self.horizontalLayout_4.addWidget(self.pushButton_min)
        self.pushButton_close = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_close.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_close.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_close.setStyleSheet("QPushButton{background:Transparent;color:blank;}QPushButton:hover{background-color:rgba(0,0,0, 0.1);}")
        self.pushButton_close.setText("")
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_4.addWidget(self.pushButton_close)
        self.horizontalLayout_5.addWidget(self.widget_6)
        self.verticalLayout_3.addWidget(self.widget_top)
        self.widget_5 = QtWidgets.QWidget(self.widget_main)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_5)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.sta_software = QtWidgets.QWidget()
        self.sta_software.setObjectName("sta_software")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.sta_software)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label = QtWidgets.QLabel(self.sta_software)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_12.addWidget(self.label)
        self.stackedWidget.addWidget(self.sta_software)
        self.sta_licenses = QtWidgets.QWidget()
        self.sta_licenses.setObjectName("sta_licenses")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.sta_licenses)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.textEdit_licenses = QtWidgets.QTextEdit(self.sta_licenses)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.textEdit_licenses.setFont(font)
        self.textEdit_licenses.setStyleSheet("QTextEdit{background:Transparent;border:0px solid grey;}")
        self.textEdit_licenses.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_licenses.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_licenses.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_licenses.setObjectName("textEdit_licenses")
        self.horizontalLayout_11.addWidget(self.textEdit_licenses)
        self.stackedWidget.addWidget(self.sta_licenses)
        self.sta_article = QtWidgets.QWidget()
        self.sta_article.setObjectName("sta_article")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.sta_article)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.listWidget_article = QtWidgets.QListWidget(self.sta_article)
        self.listWidget_article.setStyleSheet("QListWidget{background:transparent;border:0px solid grey;margin:10px;}")
        self.listWidget_article.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_article.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_article.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget_article.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidget_article.setObjectName("listWidget_article")
        self.horizontalLayout_10.addWidget(self.listWidget_article)
        self.stackedWidget.addWidget(self.sta_article)
        self.sta_source = QtWidgets.QWidget()
        self.sta_source.setObjectName("sta_source")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.sta_source)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_10 = QtWidgets.QWidget(self.sta_source)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_9 = QtWidgets.QWidget(self.widget_10)
        self.widget_9.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_9.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.label_10 = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.verticalLayout_10.addWidget(self.widget_9)
        self.widget_11 = QtWidgets.QWidget(self.widget_10)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.listWidget_source = QtWidgets.QListWidget(self.widget_11)
        self.listWidget_source.setStyleSheet("QListWidget{background:transparent;border:0px solid grey;margin:10px;}")
        self.listWidget_source.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_source.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_source.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget_source.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidget_source.setObjectName("listWidget_source")
        self.horizontalLayout_9.addWidget(self.listWidget_source)
        self.verticalLayout_10.addWidget(self.widget_11)
        self.verticalLayout_8.addWidget(self.widget_10)
        self.stackedWidget.addWidget(self.sta_source)
        self.sta_about_us = QtWidgets.QWidget()
        self.sta_about_us.setObjectName("sta_about_us")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.sta_about_us)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_about_us_up = QtWidgets.QWidget(self.sta_about_us)
        self.widget_about_us_up.setObjectName("widget_about_us_up")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_about_us_up)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.widget_7 = QtWidgets.QWidget(self.widget_about_us_up)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.widget_7)
        self.label_6.setMinimumSize(QtCore.QSize(200, 200))
        self.label_6.setMaximumSize(QtCore.QSize(200, 200))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/images/wechat.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.verticalLayout_6.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.widget_about_us_up)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.label_7 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.verticalLayout_6.addWidget(self.widget_8)
        self.label_8 = QtWidgets.QLabel(self.widget_about_us_up)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 2)
        self.verticalLayout_6.setStretch(4, 2)
        self.verticalLayout_4.addWidget(self.widget_about_us_up)
        self.widget_about_us_down = QtWidgets.QWidget(self.sta_about_us)
        self.widget_about_us_down.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget_about_us_down.setObjectName("widget_about_us_down")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_about_us_down)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_4 = QtWidgets.QWidget(self.widget_about_us_down)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.pushButton_web_site = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_web_site.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_web_site.setStyleSheet("QPushButton{background:Transparent;color:blank;}")
        self.pushButton_web_site.setObjectName("pushButton_web_site")
        self.horizontalLayout_7.addWidget(self.pushButton_web_site)
        self.line = QtWidgets.QFrame(self.widget_4)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_7.addWidget(self.line)
        self.pushButton_web_rights = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_web_rights.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_web_rights.setStyleSheet("QPushButton{background:Transparent;color:blank;}")
        self.pushButton_web_rights.setObjectName("pushButton_web_rights")
        self.horizontalLayout_7.addWidget(self.pushButton_web_rights)
        self.line_2 = QtWidgets.QFrame(self.widget_4)
        self.line_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_7.addWidget(self.line_2)
        self.pushButton_help_us = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_help_us.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_help_us.setStyleSheet("QPushButton{background:Transparent;color:blank;}")
        self.pushButton_help_us.setObjectName("pushButton_help_us")
        self.horizontalLayout_7.addWidget(self.pushButton_help_us)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_5.addWidget(self.widget_4)
        self.label_5 = QtWidgets.QLabel(self.widget_about_us_down)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.verticalLayout_4.addWidget(self.widget_about_us_down)
        self.stackedWidget.addWidget(self.sta_about_us)
        self.sta_start = QtWidgets.QWidget()
        self.sta_start.setObjectName("sta_start")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.sta_start)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_12 = QtWidgets.QWidget(self.sta_start)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem6 = QtWidgets.QSpacerItem(20, 309, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem6)
        self.label_welcome = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_welcome.setFont(font)
        self.label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome.setObjectName("label_welcome")
        self.verticalLayout_12.addWidget(self.label_welcome)
        self.verticalLayout_11.addWidget(self.widget_12)
        self.widget_13 = QtWidgets.QWidget(self.sta_start)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_time = QtWidgets.QLabel(self.widget_13)
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.verticalLayout_13.addWidget(self.label_time)
        spacerItem7 = QtWidgets.QSpacerItem(20, 308, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem7)
        self.verticalLayout_11.addWidget(self.widget_13)
        self.stackedWidget.addWidget(self.sta_start)
        self.horizontalLayout_6.addWidget(self.stackedWidget)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.horizontalLayout_2.addWidget(self.widget_main)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_menu_soft.setText(_translate("MainWindow", "  软件安利"))
        self.pushButton_menu_source.setText(_translate("MainWindow", "  源码仓库"))
        self.pushButton_menu_article.setText(_translate("MainWindow", "  文章教程"))
        self.pushButton_menu_api.setText(_translate("MainWindow", "  接口文档"))
        self.pushButton_menu_about_us.setText(_translate("MainWindow", "  关于我们"))
        self.label_sys_info.setText(_translate("MainWindow", "00:00:00"))
        self.pushButton_feedback.setToolTip(_translate("MainWindow", "<html><head/><body><p>反馈与建议</p></body></html>"))
        self.pushButton_update.setToolTip(_translate("MainWindow", "<html><head/><body><p>检查更新</p></body></html>"))
        self.pushButton_min.setToolTip(_translate("MainWindow", "<html><head/><body><p>最小化</p></body></html>"))
        self.pushButton_close.setToolTip(_translate("MainWindow", "<html><head/><body><p>关闭</p></body></html>"))
        self.label.setText(_translate("MainWindow", "加班加点紧急制作中"))
        self.label_4.setText(_translate("MainWindow", "每行代码都是用自己有限的青春换来的无限宝藏"))
        self.label_10.setText(_translate("MainWindow", "--致每一位程序员"))
        self.label_9.setText(_translate("MainWindow", "虽然不能保证每天更新一篇\n"
"但是可以保证更新的每一篇都是干货"))
        self.label_7.setText(_translate("MainWindow", "更多精彩，敬请关注微电脑公众号"))
        self.label_8.setText(_translate("MainWindow", "http://www.toodo.fun"))
        self.pushButton_web_site.setText(_translate("MainWindow", "但行趣事"))
        self.pushButton_web_rights.setText(_translate("MainWindow", "用户协议"))
        self.pushButton_help_us.setText(_translate("MainWindow", "支持我们"))
        self.label_5.setText(_translate("MainWindow", "Copyright © 2020 Toodo.fun. All Rights Reserved."))
        self.label_welcome.setText(_translate("MainWindow", "初逢不知人如玉，再逢已是意中人"))
        self.label_time.setText(_translate("MainWindow", "TextLabel"))
import resources_rc
